---------------------
--- Order Header
---------------------
DROP TABLE if exists ORD_HDR CASCADE;
DROP SEQUENCE if exists ORD_HDR_ID_SEQ CASCADE;
CREATE SEQUENCE ORD_HDR_ID_SEQ;
CREATE TABLE ORD_HDR
(
    ORD_HDR_ID   INTEGER DEFAULT nextval('ORD_HDR_ID_SEQ'),
    ORD_ID       VARCHAR(10),
    LAST_NAME_TX VARCHAR(30),
    FRST_NAME_TX VARCHAR(20),
    ADR_1_TX     VARCHAR(30),
    ADR_2_TX     VARCHAR(30),
    CITY_TX      VARCHAR(20),
    ST_CD        VARCHAR(3),
    ZIP_CD       VARCHAR(10),
    PHON_CD      VARCHAR(13),
    ORD_TYPE_CD  VARCHAR(3),
    DLV_DT       DATE,
    CONSTRAINT ORD_HDR_PK PRIMARY KEY (ORD_HDR_ID)
);
CREATE UNIQUE INDEX ORD_HDR_I1 ON ORD_HDR (ORD_ID);
ALTER SEQUENCE ORD_HDR_ID_SEQ OWNED BY ORD_HDR.ORD_HDR_ID;
---------------------
--- Order Meta
---------------------
DROP TABLE if exists ORD_META CASCADE;
DROP SEQUENCE if exists ORD_META_ID_SEQ CASCADE;
CREATE SEQUENCE ORD_META_ID_SEQ;
CREATE TABLE ORD_META
(
    ORD_META_ID   INTEGER DEFAULT nextval('ORD_META_ID_SEQ'),
    ORD_ID       VARCHAR(10),
    ORD_STAT_CD CHAR(1) NOT NULL,
    INVC_TYPE_CD CHAR(1) NOT NULL,
    PRNT_CD CHAR(1) NOT NULL,
    UPLD_TO_WMS_CD CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT ORD_META_PK PRIMARY KEY (ORD_META_ID),
    CONSTRAINT ORD_META_FK1 FOREIGN KEY(ORD_ID) REFERENCES ORD_HDR(ORD_ID)
);
CREATE UNIQUE INDEX ORD_META_I1 ON ORD_META (ORD_ID);
ALTER SEQUENCE ORD_META_ID_SEQ OWNED BY ORD_META.ORD_META_ID;